//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        public int CommentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public string Message { get; set; }
        public Nullable<int> CommentedBy { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
